spring.application.name=consulta-service
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3307/oficina_agua
spring.datasource.username=${DB_USER:lectura}
spring.datasource.password=${DB_PASSWORD:Lectura_dev_2026}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false